#!/bin/bash
ROLL=$( zenity --forms --title "Roll Dice" \
                  --text "Select the number of dice to roll, \
                           and the number of sides" \
                  --add-entry="Number" \
                  --add-entry="sides" \
		  --add-entry="drop" \
                  --separator="d" );
ROLL=$( sed 's/d/ -d /2' <<< $ROLL )
ROLL=$( sed 's/-d $//g' <<< $ROLL )
echo $ROLL
roll $ROLL | zenity --text-info 
