#!/bin/bash

if [ ! $1 ] || [ $1 = '-h' ];
then
	echo 'USAGE: roll [-q] <num_dice>d<die_sides> [-d <drop_dice>]'
	echo ' -q = Quiet Mode: only the total is output'
	echo ' -d N = Drop: after rolling, drop the lowest N dice'
	exit 1
fi

if [ $1 = '-q' ];
then
	A=$2;
	QUIET=1;
else
	A=$1;
	QUIET=0;
fi

if [ ! $1 ] && [ "$2" = '-d' ];
then
	DROP=$3
elif [ $1 = '-q' ] && [ "$3" = '-d' ];
then
	DROP=$4
else
	DROP=0
fi

NUM=${A%%d*}
SIDES=${A##*d}
TOTAL=0
LOW_ROLL=$SIDES

NUM=$(( NUM - 1 ))

for X in $( seq 0 1 $NUM )
do
	ROLLS[X]=$(( RANDOM % SIDES + 1 ))
done

IFS=$'\n' ROLLS=($(sort <<< "${ROLLS[*]}"))
unset IFS

for X in $( seq 0 1 $NUM )
do
	if [ "$X" -lt "$DROP" ];
	then
		if [ "$QUIET" -eq 0 ];
		then
			echo "Roll $(( X + 1 )) : ${ROLLS[X]} DROP"
		fi
	elif [ "$QUIET" -eq 0 ];
	then
		echo "Roll $(( X + 1 )) : ${ROLLS[X]}"
		TOTAL=$(( TOTAL + ${ROLLS[X]} ))
	else
		TOTAL=$(( TOTAL + ${ROLLS[X]} ))
	fi
done

if [ "$QUIET" -eq 0 ];
then
	echo "Total : $TOTAL"
else
	echo "$TOTAL"
fi
