#!/bin/bash

if [ ! $1 ] || [ $1 = '-h' ];
then
	echo 'USAGE: roll [-q] <num_dice>d<die_sides> [-d <drop_dice>]'
	echo ' -q = Quiet Mode: only the total is output'
	echo ' -d N = Drop: after rolling, drop the lowest N dice'
	exit 1
fi

if [ $1 = '-q' ];
then
	A=$2;
	QUIET=1;
else
	A=$1;
	QUIET=0;
fi

NUM=${A%%d*}
SIDES=${A##*d}
TOTAL=0
LOW_ROLL=$SIDES
for X in $( seq 0 1 $NUM )
do
	ROLLS[X]=$(( RANDOM % SIDES + 1 ))
done

IFS=$'\n' ROLLS=($(sort <<< "${ROLLS[*]}"))
unset IFS

for X in $( seq 0 1 $NUM )
do
	if [ $QUIET = 0 ];
	then
		echo "Roll $X  :  ${ROLLS[X]}"
	fi
	TOTAL=$(( TOTAL + ${ROLLS[X]} ))
done

if [ $QUIET = 0 ];
then
	echo "Total : $TOTAL"
else
	echo $TOTAL
fi
